alphagov/govuk-frontend-docs

- source/sass_api_reference/index.html.md.erb
This replaces the uppercase 'R' in 'Sass API Reference' with a lowercase 'r', to match GOV.UK style.
> Fix style in Sass API reference title

- .gitignore
- config.rb
- deploy/nginx.conf
- deploy/nginx/.htpasswd
- deploy/nginx/mime.types
- manifest.yml
Switch to using the nginx buildpack to allow us to selectively enable basic authentication when visiting via the cloudapps.digital route.
Closes #25
> Add basic authentication to cloudapps.digital domain

- bin/deploy-travis
By default, CloudFoundry should deploy using the path defined in the manifest file. Remove it from the deploy script to avoid the two getting out of sync.
> Remove path to app from deploy script

- bin/deploy-travis
It looks as though the v3-zdt-push command ignores the manifest file, so we do need to specify the path separately using `-p`. To avoid having it defined in two places, we can read it out of the manifest in the same way that we get the app name.
Third time's the charm…
> Use path from manifest

- config/tech-docs.yml
Set the full service name in the config so that the page titles are correct, for example 'GOV.UK Frontend' rather than 'GOV.UK Frontend | Frontend'.
> Use full name in page title

- config.rb
- config/tech-docs.yml
Make Netlify previews (or generally anything that's not the master branch) non-indexable by search engines so that users aren't confused by finding previews of PRs.
Fixes https://github.com/alphagov/govuk-frontend-docs/issues/10
> Ensure non-master preview builds are not indexed

- deploy/nginx.conf
- source/errors/404.html.md.erb
- source/errors/generic.html.md.erb
This adds a 404 and a generic error page. The content of the pages follows what we use in the Design System website.
We include `index: false` in frontmatter to remove the pages from the site search.
I've tested the 404 page by pushing to the sandbox to see it gets picked up there.
Fixes https://github.com/alphagov/govuk-frontend-docs/issues/26
> Add 404 and generic error pages

- manifest.yml
Send logs to the existing logit-ssl-drain service we use for the Design System, by binding the service to the app.
This means that the logs will end up in the same Logit instance as the Design System logs, but we can easily filter the logs and the dashboards by app name.
Part of #27
> Bind logit-ssl-drain service to app

- config/tech-docs.yml
Including the host in the config means that the canonical URL and meta tags are generated correctly.
> Add host to tech docs configuration

- deploy/nginx.conf
- source/canary.html
This PR:
- Creates a new HTML page which will be built and deployed to `/canary.html`, containing nothing but the words ‘Tweet tweet’ (following the pattern set by [GOV.UK](gov.uk/__canary__) and also used by the [Design System](design-system.service.gov.uk/__canary__/)).
- Turns off authentication off for `/canary.html` so that it can be accessed by the health checks.
Once this work is merged into master, we can merge in https://github.com/alphagov/govuk-frontend-docs/pull/50 which will add a health check to the manifest based on whether the canary page returns 200. See https://github.com/alphagov/govuk-frontend-docs/pull/50  for more details on the health check and why this work had to split into two PRs.
> Add a page for CloundFoundry health checks

- manifest.yml
Depends on https://github.com/alphagov/govuk-frontend-docs/pull/48.
This PR adds a health check to the deployment to check if `/canary.html` returns 200. This change had to be split in two PRs because the manifest will run the health check before doing the deployment - as our existing site doesn’t yet have the canary it would fail.
I paired with PaaS tech support to test what happens with a failed deploy. We verified that the already deployed site would continue to return 200 if an “unhealthy” deploy is attempted (our test case was deleting `deploy/public/canary.html`). 
I’m told by the PaaS team that V7 of [CloudFoundry CLI](https://github.com/cloudfoundry/cli) will make these steps in the deployment process much easier to manage as we’ll be able to do our Travis deploy in one line, …
> Add health checks for CloudFoundry deployments

- source/get-started/index.html.md.erb
- source/importing-css-assets-and-javascript/index.html.md.erb
The language identifier has to be lowercase for the highlighting to work correctly.
> Fix syntax highlighting

- source/supporting-ie8/index.html.md.erb
There is a minor typo. It is using the name of the variable instead of the name of the mixin.
> Fix minor IE8 mixin typo

- .rubocop.yml
- .travis.yml
- Rakefile
- config.rb
- package.json
This PR:
- Moves linting to scripts so it can be run (Rakefile wasn't able to find the linter with `npm run lint` and the error was suppressed)
- Removes suppressing linting errors when tests are run from Rakefile
- Fixes violations picked up by Rubocop
- Runs tests on Travis
- Excludes the `vendor` folder from Rubocop because on Travis it contains the other gems which can have configs that conflict with `rubocop-govuk` which we use for our code
> Fix linting and run tests on Travis

- sassdocs_helpers.rb
- source/sass-api-reference/index.html.md.erb
- spec/sassdocs_helpers_spec.rb
At the minute, we list the items in the Sass API Reference by their group, alphabetically:
- Helpers
- Helpers / Colour
- Objects
- Settings / Assets
- Settings / Colours
- Settings / Compatibility
- Settings / Global Styles
- Settings / Ie8
- Settings / Measurements
- Settings / Media Queries
- Settings / Typography
- Tools
- General
Change the structure so that they are listed grouped by the 'layer', in the order settings, tools, then helpers, with each 'group' nested underneath:
- Settings
- Assets
- Colours
- Compatibility
- Global styles
- Ie8
- Measurements
- Media queries
- Typography
- Tools
- General tools
- Helpers
- General helpers
- Colour
- Objects
- General objects
- General
- General
The eventual plan, once we've updated the Sass documentation in govuk-frontend, is that …
> Group Sass API Reference by layers, in order

- .travis.yml
- README.md
- package-lock.json
- package.json
- source/compatibility-mode/index.html.md.erb
- source/importing-css-assets-and-javascript/index.html.md.erb
You can see an example failing build [here](https://travis-ci.com/github/alphagov/govuk-frontend-docs/builds/166856383#L749-L765):
```
Guessing --root from input files: file:///home/travis/build/alphagov/govuk-frontend-docs/deploy/public/
..................×..........................................................................................................................................................................................................................................................................................................................×................................................................................................................................................................................................................................... …
```
> Add a link checker and fix broken links

- source/install-using-precompiled-files/index.html.md.erb
'Install using npm' and 'Install using precompiled files' have the same weight of `10`, so the order of their appearance in the nav is random. 
This updates 'Install using precompiled files' to have a weight of `11`, so it sits after 'Install using npm'.
> Update weight of install-using-precompiled-files

- manifest.yml
This effectively just updates nginx from v1.17.9 to v1.17.10.
Tested by manually deploying an app to the sandbox space.
> Update nginx buildpack to v1.1.9

- source/importing-css-assets-and-javascript/index.html.md.erb
With the changes in GOV.UK Frontend v3.7.0, the preferred way to import a subset of the components has changed, with the introduction of a new index file for each component.
Importing the components using the index file avoids re-importing the 'base' (settings, tools and helpers layers) multiple times, improving compilation times.
Differentiate between importing _select bits_ of GOV.UK Frontend vs importing a single specific component.
Include `/index` by default when importing, as older Sass compilers don't support importing index files, but add a note that explains that you can remove it if you are using a newer version.
Closes #47
> Update guidance on importing parts of Frontend

- source/importing-css-assets-and-javascript/index.html.md.erb
This PR documents teams should configure their Content Security Policy to work with the inline script tag in the page template.
The reasoning for this documentation is captured in:
https://github.com/alphagov/govuk-frontend/issues/1811#issuecomment-663171834
https://github.com/alphagov/govuk-frontend-docs/issues/68
We also have a [related PR](https://github.com/alphagov/govuk-frontend/pull/1884) to test if hash in these docs matches the inline script tag in page template. 
Fixes https://github.com/alphagov/govuk-frontend-docs/issues/68
Thanks @m-green for helping to write this up 🙏
> Add documentation to configure CSP to work with inline script in page template

- source/importing-css-assets-and-javascript/index.html.md.erb
Fix style in heading from 'don't' to GOV.UK style 'do not'.
> Fix style in JavaScript heading

- source/testing-your-html/index.html.md.erb
Part of https://github.com/alphagov/govuk-frontend/issues/1830
This adds a new docs page about testing your HTML matches GOV.UK Frontend. 
Before merging we need to:
> Add docs on testing with HTML fixtures

- .travis.yml
Our deployments are currently failing due to a GPG error. This is a known issue that CF are currently working on.
This temporary fix will be removed as soon as CF have issued a fix for this.
> Temporary fix for CloudFoundry deployment issue

- .travis.yml
Removes the fix introduced in https://github.com/alphagov/govuk-frontend-docs/pull/78 as it looks like CloudFoundry have fixed the underlying issue.
> Remove temp fix for CloudFoundry issue

- source/get-started/index.html.md.erb
[Get started > Get the font and images working](https://frontend.design-system.service.gov.uk/get-started/#4-get-the-font-and-images-working).
In the current content, the number 1 is repeated after a bullet list.
> Fix broken numbering in 'Get started' content

- source/testing-your-html/index.html.md.erb
alphagov/govuk-frontend#2031 adds a new `hidden` property to the objects in the fixtures list.
Update the fixtures included in the example JSON to include the new `hidden` property, and document it in the list of properties.
Closes #86
> Document `hidden` property for test fixtures

- .travis.yml
- bin/deploy-travis
Install version 7 of the CloudFoundry CLI and use it to deploy the site to PaaS.
The cf push command in v7 has a new flag —strategy which [‘can deploy an app without causing downtime using —strategy rolling’][1] – which is equivalent to the `v3-zdt-push` command. We also no longer need to manually create the app or apply the manifest, which means we no longer need to extract the app path from the manifest.
These changes mirror the [changes made in alphagov/learn-to-code][2] which had the same problem.
~~**BEFORE MERGING, we need to remove 436095f which only exists to test the deployment before this gets merged to master.**~~
Closes #91 
[1]: https://docs.cloudfoundry.org/cf-cli/v7.html#:~:text=You%20can%20deploy%20an%20app%20without%20causing%20downtime%20using%20cf%20push%20app_name%20--s …
> Fix continuous deployment

- manifest.yml
When we set these docs up, PaaS did not support the nginx buildpack, so we had to reference the buildpack using its GitHub URL, pinning to a specific version.
PaaS now provide an nginx buildpack, so use that instead. This means whenever PaaS update their buildpacks we'll automatically use the latest version when we next deploy.
The current version of the buildpack is 1.1.18, so this effectively bumps the buildpack version from 1.1.9 to 1.1.18, and the nginx version from v1.17.10 to v1.19.4 (verified by deploying a test app to the sandbox).
Closes #94
> Use PaaS-supplied nginx buildpack

- source/supporting-ie8/index.html.md.erb
The [current IE8 content](https://frontend.design-system.service.gov.uk/supporting-ie8/#support-internet-explorer-8) doesn't specify that you only follow these steps if you've already decided to support IE8. We should call this out.
> Add contextual info to IE8 doc

- source/migrating-from-legacy-products/index.html.md.erb
Current content unnecessarily repeats "easier to."
> Remove unnecessary text from migration doc

- source/migrating-from-legacy-products/index.html.md.erb
- source/sass-api-reference/index.html.md.erb
Fixes #104 (Fix accessibility issues by updating the govuk_tech_docs gem to 2.2.0 [before 31 March])
We have to update our Tech Docs Gem to incorporate several accessibility fixes in the technical documentation template. Our [accessibility statement](https://design-system.service.gov.uk/accessibility/) (at time of writing this) references these issues. For example, as here, accessibility of tables.
According to [WCAG 2.1 success criterion 1.3.1 (Info and Relationships)](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html), 'identifying' (or marking up) headers is a good way of telling assistive tech users which row and which column, together, identify a particular cell.
However, in some of our Frontend tables (see [Remove our old …
> Update tables to meet WCAG v2.1 AA

- Gemfile.lock
Fixes [#108](https://github.com/alphagov/govuk-frontend-docs/issues/108) (Fix accessibility issues by updating the govuk_tech_docs gem to 2.2.2 [before 31 March]).
Two days ago (24 March 2021), we [updated our Tech Docs Gem to incorporate several accessibility fixes in the Technical Documentation Template](https://github.com/alphagov/govuk-frontend-docs/issues/104).
Since then, we have learned that a new version of the Template has been released to fix some outstanding issues with the previous version. For example, users being able, when they use the search field, to focus elements that are 'hidden' behind other content.
This PR will update our Tech Docs Gem to the latest version of the Template. We can then test whether users can focus elements that should remain hidden to them. Point 5 …
> Update Tech Docs Gem to fix accessibility issues

- .travis.yml
- config.rb
Part of https://github.com/alphagov/govuk-frontend-docs/issues/100
Replace instances of "master" with "main" in preparation for the default branch renaming work
Many communities on GitHub are considering renaming the default branch name of their repository from master, as this terminology can be offensive. Statements and guidance have been published by Git [here](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) and GitHub [here](https://github.com/github/renaming).
New GitHub repositories use `main` as the name for the default branch, so it makes sense that we should follow this convention, as well as matching what other teams within GDS are doing so we are consistent.
> Replace instances of master with main

- package-lock.json
- package.json
Closes https://github.com/alphagov/govuk-frontend-docs/issues/120
Note that this release of GOVUK Frontend includes changes to the link styles, but these changes are opt-in.
We are not opting-in to these changes in this PR, but we want the Sass API docs to be updated
> Update GOVUK Frontend to 3.12.0

- source/importing-css-assets-and-javascript/index.html.md.erb
Content Security Policy is defined using headers or meta tags rather than files. As it's not defined in a file you can edit, 'editing CSP files' doesn't really make sense here. The page we're linking to is a pretty general broad guide on CSP, that touches on a lot more than just how to edit it, so just refer to it as general guidance on CSP.
Also make the destination (the MDN website) part of the link text, so that someone navigating out of context still understands that it takes them to an external page.
> Tweak reference to CSP

- package-lock.json
- package.json
Closes https://github.com/alphagov/govuk-frontend-docs/issues/132
Updates govuk-frontend to version 3.13.0
> Update govuk-frontend to version 3.13.0

- source/importing-css-assets-and-javascript/index.html.md.erb
Fixes [#130](https://github.com/alphagov/govuk-frontend-docs/issues/130).
This PR adds content to the [JavaScript subsection of our Frontend docs](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#select-and-initialise-part-of-a-page).
We need to tell users ([see #2246 for original issue](https://github.com/alphagov/govuk-frontend/issues/2246)) they can add a nonce to the `js-enabled` inline script in the template. This addition allows the script to execute under a CSP (Content Security Policy).
While we recommend that users include a hash in their CSP, we've [had feedback](https://github.com/alphagov/govuk-frontend/issues/2246) that this could lead, in some circumstances, to the breaking of JavaScript components. For example: if (in the future) users …
> Update JS docs to say users can use nonce in CSP

- source/updating-with-npm/index.html.md.erb
The example of what the dependency might look like in a user's `package.json` uses a mix of single and typographic quotes.
Only double quotes are supported in JSON, so update the example to use them instead.
> Update quotes in code example

- CODEOWNERS
Part of https://github.com/alphagov/design-system-team-internal/issues/455
We need to make sure only staff can access secrets and/or deploy to production.
This commit adds a [CODEOWNERS file] to ensure that any changes to our GitHub Actions or Travis CI pipelines are reviewed by a developer, to avoid the (unlikely) scenario where a PR that changes our CI/CD is approved by someone who isn't a developer and doesn't spot the significance of the change.
Note that this file should be updated when we migrate away from Travis (https://github.com/alphagov/govuk-frontend-docs/issues/89).
[CODEOWNERS file]: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners
> Add CODEOWNERS file to protect secrets

- package-lock.json
- package.json
Closes https://github.com/alphagov/govuk-frontend-docs/issues/148
You can now use the `govuk-!-text-align-left`, `govuk-!-text-align-centre` and `govuk-!-text-align-right` CSS classes to set text alignment on elements.
This was added in [pull request #2368: Add `text-align` override classes](https://github.com/alphagov/govuk-frontend/pull/2368). Thanks to [Ed Horsford](https://github.com/edwardhorsford) for reporting this issue.
You can now pass the negative equivalent of a point from the spacing scale to the `govuk-spacing` function to get negative spacing.
For example, `govuk-spacing(1)` returns `5px`, and `govuk-spacing(-1)` returns `-5px`.
This was added in [pull request #2367: Allow `govuk-spacing` to output negative spacing](https://github.com/alphagov/govuk-frontend/pull/2367). …
> Update to GOV.UK Frontend 3.14.0

- source/importing-css-assets-and-javascript/index.html.md.erb
Fixes https://github.com/alphagov/govuk-frontend-docs/issues/156
`<YOUR-APP>/assets/images` was repeated twice. Looking at the text above, it
seems like this should be `<YOUR-APP>/assets/images` and `<YOUR-APP>/assets/fonts`
> Amend duplicated folder structure text

- .github/workflows/ci.yaml
Add upload artifact task to deploy job to share data between the build and deploy jobs so we don't need to run `npm run build` again on deploy. 
This will upload the deploy folder as an artifact so it can be downloaded and used in the deploy job.
This should allow the currently failing deployment job for for https://github.com/alphagov/govuk-frontend-docs/pull/158 to complete.
> Add task to GitHub Actions to upload artifact

- .github/workflows/ci.yaml
Deploys were failing because the manifest was expecting the app to be in the deploy folder, but the upload-artifact step was archiving only the contents of the deploy folder. This commit should fix that by changing the arguments to upload-artifact to remove the wildcard; apparently the wildcard acts to remove path elements [[1]].
Note: I'm not confident this will fix it, but there's only one way to find out! :sweat_smile:
[1]: https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions
> Fix deploys

- .github/workflows/ci.yaml
- deploy/manifest.yml
Commit f731fa1 tried to fix broken deploys by preserving the top level directory name of the deploy folder. This didn't work, files are still being archived as `public/whatever` instead of `deploy/public/whatever`. This commit tries a different tack and just moves the manifest into the deploy folder, and then ensures that only the deploy folder is present on the machine that does the deploy. This means that we don't need to worry about pushing things to PaaS that we don't want to deploy (in theory).
> Fix deploys, take #2

- .github/workflows/deploy.yaml
- .github/workflows/test.yaml
Split the `ci.yaml` workflow into two: `test.yaml` for pull request checks, and `deploy.yaml` for after merge to main. To reduce code duplication the deploy workflow calls the test workflow using the beta reusable workflow feature [[1]].
[1]: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
The advantage of splitting the workflows like this is that we can then give the entire deploy workflow a concurrency limit [[2]], without affecting test workflows. Having a concurrency limit is an alternative to the step which cancels any in-progress
deploys, which would have resulted in failed deployment messages.
---
This is the equivalent of [PR #1971 in the govuk-design-system repo](https://github.com/alphagov/govuk-design-system/pull/1971).
> Refactor GitHub Actions workflows and add concurrency limit to deploys

- package-lock.json
- package.json
Closes https://github.com/alphagov/govuk-frontend-docs/issues/155
Updates the Frontend Docs to use v4.0.0.
**Note:** the current PR updates the Frontend Docs to use the v4.0.0 *pre-release*. This PR will need to be updated for the actual release, to point to the version of GOV.UK Frontend published on `npm`.
The Frontend Docs:
- **do not** use accordions. Any guidance/tutorials referring to the accordion component still look relevant and work with the new iteration
- **do not** use `govuk-main-wrapper` or `govuk-main-wrapper--l`. Updating the sassdocs means any mentions of these mixins are removed from the docs
- **do not** use `$govuk-border-width-form-element-error`
- **do not** use summary lists or refer to them
- **do not** use the header component (not directly, this is added via the …
> Update to GOV.UK Frontend v4.0.0

- config/tech-docs.yml
The GOV.UK Design System, which includes GOV.UK Frontend, [passed its live assessment on 16 November 2021][1].
Remove the beta tag from the header, as this is now a live service.
[1]: https://www.gov.uk/service-standard-reports/gov-uk-design-system-live-reassessment
> Remove beta tag

- README.md
During `bundle install` on M1 machines, there appears to be an issue with `eventmachine-1.2.7`, which complains with the error:
```
fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
^~~~~~~~~~~~~~~
1 error generated.
```
We've managed to get past this by running `brew install openssl` and following the directions here: https://stackoverflow.com/questions/30818391/gem-eventmachine-fatal-error-openssl-ssl-h-file-not-found/31516586#31516586
This adds these instructions to the troubleshooting section of the README.
> Add troubleshooting for M1 Macs during bundle install

- README.md
While setting this repo up on my new machine, I noticed some of the links in the README were out of date.
Most have equivalent documentation in the new tech docs site structure, but I can't find any relevant docs on partials, so I've removed the link for now. It used to live on the [single page documentation](https://github.com/alphagov/tdt-documentation/blob/8549ab8d4b06372acaa69e8e9f9f7f3f9fb9da53/source/create_project/single_page/index.html.md.erb#L36).
> Fix missing links in README

- source/importing-css-assets-and-javascript/index.html.md.erb
Dart Sass v1.49.10 [also silences compiler warnings coming from mixins and functions that are defined in GOV.UK Frontend even when they're called from application stylesheets][1].
So:
- Dart Sass >= 1.33.0 < 1.35.0 – deprecation warnings are emitted that cannot be silenced
- Dart Sass >= 1.35.0 < 1.49.10 – deprecation warnings coming from ‘within’ GOV.UK Frontend can be silenced using quiet deps, but if application stylesheets call a mixin or function from GOV.UK Frontend that uses / for division the warning will still be emitted
- Dart Sass >= 1.49.10 – all deprecation warnings coming from ‘within’ GOV.UK Frontend can be silenced using quiet deps, even when coming from within GOV.UK Frontend mixins or functions called from application stylesheets
I see little benefit in distinguishing …
> Suggest Dart Sass 1.49.10 for silencing warnings

- source/installing-with-npm/index.html.md.erb
Make it more explicit that GOV.UK Frontend will drop support for LibSass and Ruby Sass at some point in the future.
> Strengthen message around LibSass and Ruby Sass

- source/importing-css-assets-and-javascript/index.html.md.erb
Adds documentation for how to install GOV.UK Frontend ES modules (new functionality, added in https://github.com/alphagov/govuk-frontend/pull/2586) 
We need to tell people how to use the new ES modules if they want to. We should also use this is an opportunity to recommend people only install the component JavaScript that their application actually needs, as it has a performance benefit in comparison to loading everything regardless of whether it's being used or not.
**Note: this should only be merged once https://github.com/alphagov/govuk-frontend/pull/2586 has been released in a new version of GOV.UK Frontend**
> Add documentation for importing GOV.UK Frontend ES modules

- source/importing-css-assets-and-javascript/index.html.md.erb
We added this guidance for govuk-frontend v4.1.0 - when we [added the ability to use ES Modules](https://github.com/alphagov/govuk-frontend/releases/tag/v4.1.0) - because our imports were not fully specified (ie: they did not have file extensions). We've [fixed this for v4.1.1](https://github.com/alphagov/govuk-frontend/pull/2658), and this guidance now looks to be unneeded.
Part of #194
> Remove unnecessary guidance for webpack

- .github/workflows/deploy.yaml
GitHub have now [made it possible to reference other workflows locally, rather than needing to specify the repo and version][1].
Update the deploy workflow, which 'uses' the test workflow, to adopt this new, simpler approach.
Mimics [a change we made to the Design System deploy workflow back in January][2]
[1]: https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
[2]: https://github.com/alphagov/govuk-design-system/commit/91da7ea612a9bed8e8942b369fd26e9c2df0a878
> Reference test workflow locally

- .github/dependabot.yml
This PR enables Dependabot updates for npm, Ruby gems and GitHub Actions
Previously only security-related updates were included
> Update all dependencies using Dependabot

- source/javascript-api-reference/index.html.md.erb
There appears to be a bug in the way that the tech docs generates unique identifies for headings.
The link to the 'Button' component in the JS API Reference from the Sass API reference is incorrect because the Sass API Reference _also_ has a heading called 'Button' and this is incorrectly taken into consideration when building the nav even though we're linking to a different page.
Work around this by adding the word component to every H2 to make the headings unique, until we can fix the bug in the tech docs gem.
> Work around table of contents bug

- package-lock.json
- package.json
Closes #269.
It only updates the version number for npm as the version number in the content is meant to reference an old version given the text preceeding it.
> Update to use govuk-frontend 4.4.1

- config.rb
This makes Sprockets point to whichever version we defined in this repository rather that the one set in its own dependencies and [loaded there](https://github.com/alphagov/tech-docs-gem/blob/d3a1545158c5f9c78caafcbbbd7ddd097fdeedcb/lib/govuk_tech_docs.rb\#L35).
This ensure we're using styles and scripts from the version we set and saves us waiting for the tech_docs_gem to have updated.
> Load our govuk-frontend package before the tech_docs_gem

- .github/dependabot.yml
This PR configures Dependabot to only allow updates to [`direct` dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow)
See https://github.com/alphagov/govuk-frontend/pull/3132 for more info:
>We regularly receive Dependabot PRs for “dependencies of dependencies” **package-lock.json** changes. It's great for [**Dependabot security updates** via Settings](https://github.com/alphagov/govuk-frontend/settings/security_analysis) it's but too noisy for [**Dependabot version updates** via `dependabot.yml`](https://github.com/alphagov/govuk-frontend/blob/main/.github/dependabot.yml)
>
>For example updates to  [`indirect` dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version …
> Configure Dependabot for direct updates only

- .github/dependabot.yml
Reduces Dependabot updates frequency so it runs weekly on Monday (default) at 10:30 (some time in the day rather than before everyone is in, in the hopes to spread who picks these up a little more). 
This change of frequency shouldn't affect when Dependabot raises security updates (according to this [bit of Dependabot's documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#frequency-of-dependabot-pull-requests))
Closes [#3349](https://github.com/alphagov/govuk-frontend/issues/3349)
> Reduce dependabot updates frequency to weekly

- source/v5-0-announcement/index.html.md.erb
This is the PR for https://github.com/alphagov/govuk-frontend-docs/issues/322
We've added the announcement to the Frontend docs site, but there wasn't an obvious place to put it and it didn't fit the Changes section that's being thought about. So we've hidden it, which means people will only be able to access it if they have the link. This should be OK as I doubt people are actively browsing the docs looking for announcements currently, and we're going to be actively sharing the link. It also carries the credibility of being published on the Frontend docs site, which is more "official" than a loosely styled PDF or a message that'll rot on Slack.
> Add hidden v5 announcement to share elsewhere

- .github/workflows/deploy.yaml
- .github/workflows/test.yaml
- package-lock.json
- package.json
This PR includes a couple of GitHub Actions fixes:
1. The npm script `check-links` can fail silently
2. The checks are duplicates across `pull` and `pull_request` events
Matching the [GOV.UK Design System `check-links` arguments](https://github.com/alphagov/govuk-design-system/commit/85371227743245c38c6a25c89eb0e3b2157f8174) found a `--skip` argument typo
We have a broken image that should skipped with ~`property="og:url"`~ `property="og:image"`
* https://github.com/alphagov/tech-docs-gem/issues/194
> Preview v5: GitHub Actions fixes

- lib/sassdocs_helpers.rb
- source/install-using-precompiled-files/index.html.md.erb
Removes some IE8 references from HTML condition statements and helper code
Although the **Support Internet Explorer 8** page is actually removed in:
* https://github.com/alphagov/govuk-frontend-docs/pull/332
> Preview v5: Remove references to IE8 in code

- source/get-started/index.html.md.erb
- source/importing-css-assets-and-javascript/index.html.md.erb
- source/install-using-precompiled-files/index.html.md.erb
Completes a task from: https://github.com/alphagov/govuk-frontend-docs/issues/308
> Preview v5: Update template with "supported" check

- source/compatibility-mode/index.html.md.erb
- source/configure-components-with-javascript/index.html.md.erb
- source/get-started/index.html.md.erb
- source/importing-css-assets-and-javascript/index.html.md.erb
- source/install-using-precompiled-files/index.html.md.erb
- source/javascript-api-reference/index.html.md.erb
- source/localise-govuk-frontend/index.html.md.erb
- source/testing-your-html/index.html.md.erb
- source/use-nunjucks/index.html.md.erb
Aligns all our examples to use `<script type="module">` for https://github.com/alphagov/govuk-frontend-docs/issues/308
Need to consider (maybe) adding a UMD example for those that need `window.GOVUKFrontend` support
> Preview v5: Update examples using ES modules

- lib/sassdocs_helpers.rb
- spec/sassdocs_helpers_spec.rb
This PR updates the GitHub URL helper for GOV.UK Frontend v5
For now, I've maintained backwards compatibility with v4
> Preview v5: Update application paths for `govuk-frontend@5`

- package-lock.json
- package.json
**This PR cherry-picks 3e3adb6e2f28aa14e7706fecce81b34b11f5d967 from #335 into the main branch to unblock merging PRs to main because of link checks failing ([Example](https://github.com/alphagov/govuk-frontend-docs/actions/runs/5877869593/job/15943224377?pr=338))**
---
We often see sucessful log output from `tap-spot` followed by a non-zero error code so we’ve swapped it for `tap-mocha-reporter` like we did on GOV.UK Design System
I’ve also added the `--canonicalroot` flag to check more internal assets that would have previously been skipped as external
Note: We still have a broken share image
* https://github.com/alphagov/tech-docs-gem/issues/194
> Fix link checker reporting

- source/get-started/index.html.md.erb
In point 2 of section "5. Get the JavaScript working" there was an incorrect reference to the node_modules folder which was typed as as node-modules (hyphen instead of underscore).
This change fixes that small issue.
> Correct node_modules folder name in index.html.md.erb

- source/importing-css-assets-and-javascript/index.html.md.erb
As we decided that to start with, [we’d limit our public API to “we throw errors”](https://github.com/alphagov/govuk-frontend/issues/4074#issuecomment-1731127591), we don’t have any specific errors to document as part of our [JavaScript API Reference](https://frontend.design-system.service.gov.uk/javascript-api-reference/). 
I think we don't need more than [an update to “Select and initialise individual components” (Netlify preview)](https://document-errors--govuk-frontend-docs-preview.netlify.app/importing-css-assets-and-javascript/#select-and-initialise-an-individual-component), which this PR adds.
Only other thing I could think of may be to discuss “Initialising components” to the JavaScript API Reference to explain that initAll doesn’t throw but logs and individual initialisation …
> Add explanation that individual initialisation will throw errors

- package-lock.json
- source/browser-support/index.html.md.erb
Adds the content of [the draft of our summary of our browser support strategy (internal link)](https://docs.google.com/document/d/10rkRaoPo_1nVw1hmYSSUKEttBKrY9OSM-6bI-5J5QJ4/edit) to the docs. 
Couldn't remember if/where we said we'd put it in the menu, so just appended it to the list. Please feel free to update the PR and put it at another level.
Part of #340 (the issue needs to wait for [the full guidance to have been merged on the `govuk-frontend` repo](https://github.com/alphagov/govuk-frontend/pull/4381) before being closed).
> Add new page describing our browser support strategy

- source/changes-to-govuk-frontend-v5/index.html.md.erb
- source/staying-up-to-date/index.html.md.erb
- source/v5-0-announcement/index.html.md.erb
When browsing the [v5 preview site](https://release-5-0--govuk-frontend-docs-preview.netlify.app), some links sneakily direct users to the [v4 release site](https://frontend.design-system.service.gov.uk)
> Prevent confusion from preview site linking to release site

- source/v5-0-announcement/index.html.md.erb
Archives the v5 announcement - no longer needed now that we have merged the docs.
> Preview v5: Archive the announcement page

- .github/workflows/test.yaml
- .nvmrc
- package-lock.json
- package.json
This PR allows Node.js LTS ‘Iron’ (v20) to install dependencies for **GOV.UK Frontend Docs**
>GOV.UK Frontend requires Node.js version 12.17.0 or later to support ECMAScript modules. Where possible, we recommend you install the latest Long Term Support (LTS) version.
Changes included:
1. **Updating [.nvmrc](https://github.com/alphagov/govuk-frontend/blob/main/.nvmrc)** for Node.js 20
So tools like [nvm](https://github.com/nvm-sh/nvm#readme) and [asdf](https://github.com/asdf-vm/asdf#readme) allow the `lts/iron` LTS release
3. **Add the [package.json `engines.node` range](https://github.com/alphagov/govuk-frontend/blob/main/package.json#L6)**
Ensures `npm install` and other scripts check the local Node.js version is allowed
3. **Add the [package.json `engines.npm` …
> Allow Node.js LTS ‘Iron’ (v20) release version

- netlify.toml
Adds Netlify configuration for proxying requests to `/security.txt` and `/.well-known/security.txt`. Our current site doesn't have those, but it'll make Frontend Docs do the same as Design System on that front.
Closes #382 as [the Frontend Docs NGINX configuration](https://github.com/alphagov/govuk-frontend-docs/blob/main/deploy/nginx.conf) has no redirects.
> Proxy requests for security.txt

- source/configure-components-with-javascript/index.html.md.erb
- source/configure-components/index.html.md.erb
- source/importing-css-assets-and-javascript/index.html.md.erb
- source/javascript-api-reference/index.html.md.erb
- source/localise-govuk-frontend/index.html.md.erb
- source/use-nunjucks/index.html.md.erb
We have lots of JavaScript examples split across:
* [**Import CSS, assets and JavaScript**](https://release-5-0--govuk-frontend-docs-preview.netlify.app/importing-css-assets-and-javascript/)
* [**Configure components with JavaScript**](https://release-5-0--govuk-frontend-docs-preview.netlify.app/configure-components-with-javascript/)
This makes it difficult to add information about:
1. Errors in the browser console
2. Different flavours of JavaScript
3. Benefits of using a bundler
It's hard to document ways to import JavaScript when the "importing" page is full of configuration examples
This PR adds a new [**Configure components** page](https://deploy-preview-395--govuk-frontend-docs-preview.netlify.app/configure-components/)
It was previously called **Configure components with …
> Organise JavaScript configuration documentation

- netlify.toml
Redirects the 'Configure components' page, previously at `/configure-components-with-javascript/` ([link to preview site with the old path](https://deploy-preview-401--govuk-frontend-docs-preview.netlify.app/configure-components-with-javascript/)) to its new location `/configure-components/`.
> Configure components redirect

- source/configure-components/index.html.md.erb
- source/javascript-api-reference/index.html.md.erb
This PR simplifies the "JavaScript API Reference" introduction by:
1. Clearly linking to the new "Configure components" page
2. Matching config wording to "Configure components" headings
3. Adding anchor links to each component by name
4. Removing the `Button` example
Regarding 4) we have better `CharacterCount` examples on "Configure components" already
I've also clarified a few mix-ups between "configuration" and "options" such as:
```patch
- Read the JavaScript API Reference for the configuration accepted by each component.
+ Read the JavaScript API Reference for the list of options in each component configuration.
```
```patch
- Read the JavaScript API Reference for the configuration accepted by `initAll`.
+ Read the JavaScript API Reference for the list of components in the `initAll` …
```
> Update JavaScript API Reference for v5

- source/browser-support/index.html.md.erb
- source/changes-to-govuk-frontend-v5/index.html.md.erb
- source/v4/index.html.md.erb
Adds content drafted for the following pages to the repository:
- [Browser support (internal link)](https://docs.google.com/document/d/10rkRaoPo_1nVw1hmYSSUKEttBKrY9OSM-6bI-5J5QJ4/edit) at [/browser-support/](https://deploy-preview-403--govuk-frontend-docs-preview.netlify.app/browser-support/)
- [Changes to GOV.UK Frontend v5](https://docs.google.com/document/d/1q2StFWP-kEKRPT_ytD_qkpFW2V3BuvH3ARaTSHtM67Y/edit) at [/changes-to-govuk-frontend-v5](https://deploy-preview-403--govuk-frontend-docs-preview.netlify.app/changes-to-govuk-frontend-v5/)
Also adds the notice for how long we'll support v4 on the "homepage" of the v4 docs.
> Add drafted content to the repository

- source/importing-css-assets-and-javascript/index.html.md.erb
- source/v4/importing-css-assets-and-javascript/index.html.md.erb
Just spotted an [old typo](https://github.com/alphagov/govuk-frontend-docs/commit/fc9904f53dcb8fe01b7d6fd74cf265bd2a7670d1) in one of our example selectors
> Fix missing double quote in `$radios` selector

- source/changes-to-govuk-frontend-v5/index.html.md.erb
I was hoping to find a place where the fixed v5 accessibility issues were listed in the v5 documentation. Is it alright if a new section is added here?
I pulled the issues from this Github query: https://github.com/alphagov/govuk-frontend/issues?q=milestone%3Av5.0+label%3Aaccessibility
> Add accessibility change list to the v5 changes page

- source/sass-api-reference/index.html.md.erb
This issue prevented tables with multiple rows from rendering correctly
It was caused by `prettier --write` when run on Markdown files in https://github.com/alphagov/govuk-frontend-docs/commit/df2fe5e4b9fc7aa306ad2595a7e75c0f914931c9
The rendering issue was not present in the [v4.x documentation](https://frontend.design-system.service.gov.uk/v4/) as shown:
* [**Spacing** mixin `govuk-responsive-margin` on v4.x](https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-responsive-margin)
* [**Spacing**  mixin `govuk-responsive-margin` on v5.x](https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-responsive-margin) – broken on `main`
* [**Spacing**  mixin `govuk-responsive-margin` on v5.x](https://deploy-preview-418--govuk-frontend-docs-preview.netlify.app/sa …
> Fix Markdown parameter rendering due to empty line after row

- netlify.toml
This mirrors the changes made in https://github.com/alphagov/govuk-design-system/pull/3417, allowing files with ‘fingerprint’ hashes in their filenames to be treated as immutable and cached indefinitely.
Unfortunately in this repo at the minute that only includes the font assets included from GOV.UK Frontend.
Closes #383
> Configure Netlify Cache-Control headers

- source/import-css/index.html.md.erb
Update the documentation to suggest importing using `index` files rather the now-deprecated `all` files following the changes in alphagov/govuk-frontend/pull/4955.
Part of https://github.com/alphagov/govuk-frontend/issues/4960.
> Use `index` for Sass entrypoints rather than `all`

- config.rb
- lib/package_contents.rb
- source/import-css/index.html.md.erb
- spec/package_contents_spec.rb
Provide a more exhaustive example of how to import specific bits of our Sass, allowing users to understand what's possible without having to go digging through the code.
Specifically, document the full list of components and overrides as they comprise the greatest percentage of the generated CSS (70% and 15% respectively) and are least likely to be fully used.
I've also opted to include some approximate percentages to give users an indication of the weight of each layer. These percentages will be less accurate over time as the composition of our Sass changes, but I think they're likely to remain accurate enough to be useful.
👉🏻 [Have a look](https://deploy-preview-445--govuk-frontend-docs-preview.netlify.app/import-css/#import-specific-parts-using-sass) 👀
> Expand documentation on importing specific bits of the Sass

- source/configure-components/index.html.md.erb
- source/import-javascript/index.html.md.erb
- source/javascript-api-reference/index.html.md.erb
- source/localise-govuk-frontend/index.html.md.erb
> [!WARNING]
> This PR should only be merged after the next release of GOV.UK Frontend
Updates the Frontend docs to reflect the [addition of a new `createAll` function](https://github.com/alphagov/govuk-frontend/pull/4975) to initialise all instances of a specific component on the page.
Also moves the 'Initialise only part of a page' to the 'Import JavaScript' page, rather than 'Configure components' to regroup both how to import and initialise components.
[Each commit](https://github.com/alphagov/govuk-frontend-docs/pull/443/commits) details the changes of a specific page.
Closes alphagov/govuk-frontend#4945
> Update 'Import JavaScript' page to use new `createAll` function

- source/staying-up-to-date/index.html.md.erb
Projects using a monorepo to group multiple packages in a single repository will likely have `govuk-frontend` as a dependency of one of the repository's packages rather than at the root of their repository.
If they'd use the commands we provide as is, they'd end up installing `govuk-frontend` in the root `package.json`, while the one in the package actually using `govuk-frontend` remains in their old version. This means the project wouldn't effectively be upgraded.
There are many tools to manage a monorepo, evolving at their own pace. I don't think its our responsibility to provide the exact command to use for each of them, however I think adding a little warning would save people some headaches.
A couple of toughts behind the choices:
- Inset text helps grab the attention a little, in a …
> Add note about adapting commands when updating GOV.UK Frontend for monorepos

- .github/dependabot.yml
This should make Dependabot look at updating our own dependencies before the other groups.
> Add group for our own dependencies in Dependabot config

- source/building-your-own-javascript-components/index.html.md.erb
> [!IMPORTANT]
> This PR should only be merged after [the next release of GOV.UK Frontend v5](https://github.com/alphagov/govuk-frontend/issues/5386).
Adds [the documentation for the public JavaScript API](https://deploy-preview-468--govuk-frontend-docs-preview.netlify.app/building-your-own-javascript-components/) parts implemented so far, which help you build and initialise your own components.
Fixes #467
> Add drafted content for 'Building your own JavaScript components'

- source/import-css/index.html.md.erb
- source/import-javascript/index.html.md.erb
- source/installing-with-npm/index.html.md.erb
* Add some links to the new 'Building your own components' page (see #468)
* Fixes the title of the 'Import CSS' page
* Updates the 'Get the JavaScript working' to encourage importing individual components (missed in 5.4.0).
This PR is best reviewed commit by commit, each affecting the following sections:
1. ['Before you start' in 'Import JavaScript'](https://deploy-preview-469--govuk-frontend-docs-preview.netlify.app/import-javascript/#before-you-start)
2. ['Import individual components' in 'Import JavaScript'](https://deploy-preview-469--govuk-frontend-docs-preview.netlify.app/import-javascript/#import-individual-components)
3. ['Get the JavaScript working' in 'Install with Node.js package manager (npm)'](https://deploy-preview-469--govuk-frontend-docs-preview.netlify.app/installing-with …
> Update existing pages ahead of 5.7.0 release

- source/building-your-own-javascript-components/index.html.md.erb
Propose the use of a shorthand ambient module declaration rather than re-defining `get $root`,
which has the advantage to not add extra JavaScript code to support TypeScript.
> Update workaround for accessing `this.$root` with TypeScript

- .github/workflows/test.yaml
We're having some problems with Ubuntu 24, so fixing to 22 while we sort them.
> Fix runner Ubuntu to 22

- source/building-your-own-javascript-components/index.html.md.erb
> [!IMPORTANT]
> Only to be merged as part of the 5.8.0 release
Adds the [content drafted ahead of the release (internal link)](https://docs.google.com/document/d/1Ptivt7MxnJeUoEv3Tm42iB-MkMuuWd--mhKX1B52CPQ/edit\?tab\=t.0) to the ['Building your JavaScript components' page (preview)](https://deploy-preview-488--govuk-frontend-docs-preview.netlify.app/building-your-own-javascript-components/#building-configurable-components).
I went through the code blocks paying attention to smart quotes and indentation, but it's possible I missed some so please keep an eye for those during the review.
Fixes #486
> Add section about 'Building configurable components'

- source/installing-with-npm/index.html.md.erb
The intentation was making Markdown consider the fenced block part of the content rather than the start of the code block and rendering the following on the page:
~~~
```scss
@import "node_modules/govuk-frontend/dist/govuk/index";
```
~~~
It now correctly renders:
```scss
@import "node_modules/govuk-frontend/dist/govuk/index";
```
Before: https://frontend.design-system.service.gov.uk/installing-with-npm/#get-the-css-assets-and-javascript-working
After: https://deploy-preview-506--govuk-frontend-docs-preview.netlify.app/installing-with-npm/#get-the-css-working
Fixes #505
> Fix misformatted codeblock in install-with-npm page

- source/staying-up-to-date/index.html.md.erb
We don't do pre-releases very often, so the version behind the "next" tag is usually pretty out of date.
We can encourage folks to try the "next" tag via comms when we need wider testing. Most of the active port maintainers are already pretty on top of this anyway.
> Remove pre-release installation instructions

- .github/dependabot.yml
- CODEOWNERS
Dependabot's `reviewers` option is being removed on 27th May, with its functionality being merged with the `CODEOWNERS` file, [as described on the GitHub blog](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/).
- Updates the `CODEOWNERS` file to include the **root** `package.json` and `package-lock.json` files explicitly, to match npm dependencies being protected by the `reviewers` option in Dependabot's config.
- Updates the `CODEOWNERS` file to include `Gemfile` and `Gemfile.lock`, to match the prior protection for gem updates.
- Updates the `CODEOWNERS` file to include the `CODEOWNERS` file itself, requiring approval from codeowners to change it in future. [This is a recommended security …
> Remove deprecated `reviewers` option from Dependabot config

- source/changes-to-govuk-frontend-v5/index.html.md.erb
Update to Changes to GOV.UK Frontend v5.0.0 to reflect the work we're doing to support adopting the GOV.UK rebrand.
Users of v4 and v5 are able to understand the context of us supporting an update to the rebrand. We also include that we are not planning to support any future updates to v4.
> Draft changes to tech docs for v4 brand update

- package-lock.json
- package.json
Updates the main site from 5.10.1 to 5.10.2 and the v4 site from 4.9.0 to 4.10.0
> Update govuk-frontend versions

- .github/dependabot.yml
We’ve moved to monthly Dependabot checks, but didn’t update the comment.
Given the config is pretty self-explanatory, remove the BARE-FACED LIES rather than update them.
> Remove incorrect Dependabot schedule comment

- package-lock.json
- package.json
Following the [5.11.2 release of GOV.UK Frontend](https://github.com/alphagov/govuk-frontend/releases/tag/v5.11.2)
> Update GOV.UK Frontend to 5.11.2

- source/building-your-own-javascript-components/index.html.md.erb
- source/configure-components/index.html.md.erb
- source/import-javascript/index.html.md.erb
- source/javascript-api-reference/index.html.md.erb
- source/localise-govuk-frontend/index.html.md.erb
- source/v4/importing-css-assets-and-javascript/index.html.md.erb
- source/v4/javascript-api-reference/index.html.md.erb
- source/v4/localise-govuk-frontend/index.html.md.erb
This PR aimed to fix a ~`Component`~ `component` typo in the error handler example:
```patch
- function notifyErrorMonitoringService(error, { Component, element, config }) {
+ function notifyErrorMonitoringService(error, { component, element, config }) {
```
But I also noticed an incorrect link to copying assets and some other minor improvements
> Fix typo in error handler context and other suggestions
